/*Consulta-1*/
/*Consultar el lugar del siniestro, quien reporto y el motivo de la misma.*/
select
SERVICIO.DIRECCION_SERVICIO AS LUGAR,
LLAMADAS.USUARIO_LLAMADA AS REPORTANTE,
LLAMADAS.MOTIVO_LLAMADA AS MOTIVO
FROM SERVICIO 
INNER JOIN LLAMADA_SERVICIO ON LLAMADA_SERVICIO.ID_SERVICIO=SERVICIO.ID_SERVICIO
INNER JOIN LLAMADAS ON LLAMADAS.ID_LLAMADA=LLAMADA_SERVICIO.ID_LLAMADA;

/*Consulta-2*/
/*Mostar dentro de cada rango de oficial del cuerpo de bomberos cuantos cursos se han realizados por cada bombero.*/
select 
(BOMBERO.NOMBRE_BOMBERO || BOMBERO.APELLIDO_BOMBERO) as BOMBERO,
RANGO.DESCRIPCION_RANGO as RANGO,
count(CURSO.ID_CURSO) as CANTIDAD_CURSOS
from BOMBERO
inner join RANGO on RANGO.ID_RANGO=BOMBERO.ID_RANGO
inner join BOMBERO_CURSO on BOMBERO_CURSO.ID_BOMBERO=BOMBERO.ID_BOMBERO
inner join CURSO on CURSO.ID_CURSO=BOMBERO_CURSO.ID_CURSO
group by BOMBERO, RANGO


/*Consulta-3*/
/*Consultar la cantidad de veces que un bombero ha faltado.*/
select 
(BOMBERO.NOMBRE_BOMBERO || BOMBERO.APELLIDO_BOMBERO) as BOMBERO,
count(SERVICIOS_BOMBEROS.ID_SERVICIO)as CANTIDAD_FALTAS
from BOMBERO
inner join SERVICIOS_BOMBEROS on SERVICIOS_BOMBEROS.ID_BOMBERO=BOMBERO.ID_BOMBERO
where SERVICIOS_BOMBEROS.ASISTENCIA_SB='NO'
group by BOMBERO;


/*Consulta-4*/
/*Mostrar cuantas personas le han dado mantenimiento a un vehículo.*/

select 
VEHICULO.PLACA_VEHICULO as placa,
count(BOMBERO.ID_BOMBERO) as CANTIDAD_PERSONAS
from VEHICULO
inner join MANTENIMIENTO on MANTENIMIENTO.ID_VEHICULO=VEHICULO.ID_VEHICULO
inner join BOMBERO on MANTENIMIENTO.ID_BOMBERO=BOMBERO.ID_BOMBERO
group by placa;



/*Consulta--Adicional*/
/*Consultar la puntuación de cada bombero y la actividad de servicio que realiza.*/


SELECT 
(BOMBERO.NOMBRE_BOMBERO || BOMBERO.APELLIDO_BOMBERO)AS BOMBERO,
SERVICIO.ID_SERVICIO,
SERVICIOS_BOMBEROS.DETALLE_SB,
SERVICIOS_BOMBEROS.PUNTUACION_SB
FROM SERVICIO
INNER JOIN SERVICIOS_BOMBEROS ON SERVICIOS_BOMBEROS.ID_SERVICIO=SERVICIO.ID_SERVICIO
INNER JOIN BOMBERO ON BOMBERO.ID_BOMBERO=SERVICIOS_BOMBEROS.ID_BOMBERO
ORDER BY BOMBERO;